# Generated by Django 6.0.1 on 2026-01-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionHourlyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=5)),
                ('datetime', models.DateTimeField()),
                ('load_mw', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StateDailyLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('energy_mu', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DailyPredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('load_mw', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('state', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StateLoad5Min',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField()),
                ('load_mw', models.FloatField(blank=True, null=True)),
                ('brpl', models.FloatField(blank=True, null=True)),
                ('bypl', models.FloatField(blank=True, null=True)),
                ('ndpl', models.FloatField(blank=True, null=True)),
                ('ndmc', models.FloatField(blank=True, null=True)),
                ('mes', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-datetime'],
                'constraints': [models.UniqueConstraint(fields=('state', 'datetime'), name='unique_state_datetime_5min')],
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('datetime', models.DateTimeField(db_index=True)),
                ('frequency', models.CharField(choices=[('5min', '5 Minutes'), ('15min', '15 Minutes'), ('hourly', 'Hourly'), ('daily', 'Daily')], default='hourly', max_length=10)),
                ('temperature_c', models.FloatField()),
                ('humidity_pct', models.FloatField(blank=True, null=True)),
                ('rain_mm', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(choices=[('open_meteo', 'Open Meteo'), ('nasa_power', 'NASA POWER'), ('imd', 'IMD'), ('manual', 'Manual')], default='open_meteo', max_length=20)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('state', 'datetime', 'frequency', 'source'), name='unique_state_datetime_weather')],
            },
        ),
    ]
