# Generated by Django 6.0.1 on 2026-02-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='frequency',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='weather',
            name='source',
            field=models.CharField(max_length=20),
        ),
    ]
